Repository ourchitecture/chomping-at-the-bit, pull requests merged in 2022-04, with the labels that each got.

#16 ci: make pr
  .github/workflows/gh-docs.yaml
  projects/webapp/Dockerfile
Labels: enhancement

#18 docs: auto-generated documentation
  projects/webapp/build.sh
  projects/webapp/containers.sh
  projects/webapp/e2e-tests.sh
  projects/webapp/lint.sh
  projects/webapp/start.sh
  projects/webapp/stop.sh
  projects/webapp/unit-tests.sh
Labels: documentation

#19 test: docs build 001
  projects/webapp/src/views/HomePage.vue
  projects/webapp/tests/unit/example.spec.ts
Labels: enhancement

#21 fix: github 404 for client-side routing
  projects/webapp/release.sh
  projects/webapp/src/views/HomePage.vue
  projects/webapp/tests/unit/example.spec.ts
Labels: bug, enhancement

#24 docs: auto-generated documentation
  docs/404.html
  docs/css/app.e78f7e6f.css
  docs/index.html
  docs/js/app.4832937d.js.map
  docs/js/app.dad22c7e.js
  docs/js/app.dad22c7e.js.map
  projects/webapp/e2e-test.sh
  projects/webapp/unit-test.sh
Labels: documentation

#25 feat: mission, vision and values
  .github/workflows/gh-docs.yaml
  makefile
  projects/webapp/README.md
  projects/webapp/install.sh
  projects/webapp/makefile
  projects/webapp/package.json
  projects/webapp/public/assets/book/chomping-at-the-bit.pdf
  projects/webapp/public/assets/icon/business-model-canvas/channels_dark.svg
  projects/webapp/public/assets/icon/business-model-canvas/channels_light.svg
  projects/webapp/public/assets/icon/business-model-canvas/key-resources_dark.svg
  projects/webapp/public/assets/icon/business-model-canvas/key-resources_light.svg
  projects/webapp/public/assets/icon/business-model-canvas/revenue-streams_dark.svg
  projects/webapp/public/assets/icon/business-model-canvas/revenue-streams_light.svg
  projects/webapp/src/App.vue
  projects/webapp/src/components/OurBusinessCanvas.vue
  projects/webapp/src/components/OurDemoCo.vue
  projects/webapp/src/components/OurMission.vue
  projects/webapp/src/components/OurValues.vue
  projects/webapp/src/components/OurVision.vue
  projects/webapp/src/main.ts
  projects/webapp/src/theme/variables.css
  projects/webapp/src/views/HomePage.vue
  projects/webapp/tests/e2e/videos/test.js.mp4
  projects/webapp/yarn.lock
Labels: documentation, enhancement

#27 fix: icons and book link
  .vscode/settings.json
  projects/webapp/public/index.html
  projects/webapp/src/views/HomePage.vue
Labels: bug

#29 fix: link to book
  projects/webapp/src/views/HomePage.vue
Labels: bug

#31 feat: diagram updates
  makefile
  projects/book/makefile
  projects/book/src/assets/graphics/diagrams/value-delivery-resources.drawio
  projects/book/src/assets/graphics/diagrams/value-delivery-resources.png
  projects/book/src/assets/graphics/diagrams/value-delivery-structures.drawio
  projects/book/src/assets/graphics/diagrams/value-delivery-structures.png
  projects/book/src/introduction.adoc
  projects/book/src/resources.adoc
  projects/book/src/structures.adoc
  projects/webapp/public/assets/book/chomping-at-the-bit.pdf
Labels: enhancement

#32 docs: auto-generated documentation
  docs/assets/book/chomping-at-the-bit.pdf
Labels: documentation

#33 chore: git sync tasks
  makefile
Labels: enhancement

#39 feat: dark mode toggle
  projects/webapp/src/App.vue
  projects/webapp/src/main.ts
  projects/webapp/src/theme/variables.css
  projects/webapp/src/views/HomePage.vue
  projects/webapp/vue.config.js
  projects/webapp/yarn.lock
Labels: enhancement

#41 feat: avatars
  projects/media/stock.adobe.com/LICENSE.md
  projects/media/stock.adobe.com/avatar-01-01.svg
  projects/media/stock.adobe.com/avatar-01-01_256h.png
  projects/media/stock.adobe.com/avatar-01-02.svg
  projects/media/stock.adobe.com/avatar-01-02_256h.png
  projects/media/stock.adobe.com/avatar-01-03.svg
  projects/media/stock.adobe.com/avatar-01-03_256h.png
  projects/media/stock.adobe.com/avatar-01-04.svg
  projects/media/stock.adobe.com/avatar-01-04_256h.png
  projects/media/stock.adobe.com/avatar-01-05.svg
  projects/media/stock.adobe.com/avatar-01-05_256h.png
  projects/media/stock.adobe.com/avatar-01-06.svg
  projects/media/stock.adobe.com/avatar-01-06_256h.png
  projects/media/stock.adobe.com/avatar-02-01.svg
  projects/media/stock.adobe.com/avatar-02-01_256h.png
  projects/media/stock.adobe.com/avatar-02-02.svg
  projects/media/stock.adobe.com/avatar-02-02_256h.png
  projects/media/stock.adobe.com/avatar-02-03.svg
  projects/media/stock.adobe.com/avatar-02-03_256h.png
  projects/webapp/public/assets/avatars/avatar-01-01_256h.png
  projects/webapp/public/assets/avatars/avatar-01-02_256h.png
  projects/webapp/public/assets/avatars/avatar-01-03_256h.png
  projects/webapp/public/assets/avatars/avatar-01-04_256h.png
  projects/webapp/public/assets/avatars/avatar-01-05_256h.png
  projects/webapp/public/assets/avatars/avatar-01-06_256h.png
  projects/webapp/public/assets/avatars/avatar-02-01_256h.png
  projects/webapp/public/assets/avatars/avatar-02-02_256h.png
  projects/webapp/public/assets/avatars/avatar-02-03_256h.png
  projects/webapp/src/components/avatars/avatar-01-01.vue
  projects/webapp/src/components/avatars/avatar-01-02.vue
  projects/webapp/src/components/avatars/avatar-01-03.vue
  projects/webapp/src/components/avatars/avatar-01-04.vue
  projects/webapp/src/components/avatars/avatar-01-05.vue
  projects/webapp/src/components/avatars/avatar-01-06.vue
  projects/webapp/src/components/avatars/avatar-02-01.vue
  projects/webapp/src/components/avatars/avatar-02-02.vue
  projects/webapp/src/components/avatars/avatar-02-03.vue
  projects/webapp/src/router/index.ts
  projects/webapp/src/views/AvatarsPage.vue
  projects/webapp/src/views/HomePage.vue
Labels: enhancement

#42 docs: auto-generated documentation
  docs/404.html
  docs/assets/avatars/avatar-01-01_256h.png
  docs/assets/avatars/avatar-01-02_256h.png
  docs/assets/avatars/avatar-01-03_256h.png
  docs/assets/avatars/avatar-01-04_256h.png
  docs/assets/avatars/avatar-01-05_256h.png
  docs/assets/avatars/avatar-01-06_256h.png
  docs/assets/avatars/avatar-02-01_256h.png
  docs/assets/avatars/avatar-02-02_256h.png
  docs/assets/avatars/avatar-02-03_256h.png
  docs/css/app.35d95a3d.css
  docs/css/app.8e980ebe.css
  docs/index.html
  docs/js/app.d7250444.js
  docs/js/app.d7250444.js.map
  docs/js/app.dd681ed2.js
  docs/js/app.dd681ed2.js.map
  docs/js/chunk-vendors.936ea916.js
  docs/js/chunk-vendors.936ea916.js.map
  docs/js/chunk-vendors.bea49107.js.map
Labels: documentation

#43 fix: relative link
  projects/webapp/src/views/HomePage.vue
Labels: bug

#45 feat: avatar names
  projects/media/stock.adobe.com/LICENSE.md
  projects/media/stock.adobe.com/avatar-02-04.svg
  projects/media/stock.adobe.com/avatar-02-04_256h.png
  projects/media/stock.adobe.com/avatar-02-05.svg
  projects/media/stock.adobe.com/avatar-02-05_256h.png
  projects/media/stock.adobe.com/avatar-02-06.svg
  projects/media/stock.adobe.com/avatar-02-06_256h.png
  projects/webapp/package.json
  projects/webapp/public/assets/avatars/avatar-02-04_256h.png
  projects/webapp/public/assets/avatars/avatar-02-05_256h.png
  projects/webapp/public/assets/avatars/avatar-02-06_256h.png
  projects/webapp/src/components/avatars/avatar-02-04.vue
  projects/webapp/src/components/avatars/avatar-02-05.vue
  projects/webapp/src/components/avatars/avatar-02-06.vue
  projects/webapp/src/human-names.d.ts
  projects/webapp/src/views/AvatarsPage.vue
  projects/webapp/yarn.lock
Labels: enhancement

#47 feat: avatar profiles
  projects/media/stock.adobe.com/LICENSE.md
  projects/media/stock.adobe.com/avatar-01-07.svg
  projects/media/stock.adobe.com/avatar-01-07_256h.png
  projects/media/stock.adobe.com/avatar-01-08.svg
  projects/media/stock.adobe.com/avatar-01-08_256h.png
  projects/media/stock.adobe.com/avatar-01-09.svg
  projects/media/stock.adobe.com/avatar-01-09_256h.png
  projects/media/stock.adobe.com/avatar-01-10.svg
  projects/media/stock.adobe.com/avatar-01-10_256h.png
  projects/media/stock.adobe.com/avatar-01-11.svg
  projects/media/stock.adobe.com/avatar-01-11_256h.png
  projects/media/stock.adobe.com/avatar-01-12.svg
  projects/media/stock.adobe.com/avatar-01-12_256h.png
  projects/media/stock.adobe.com/avatar-01-13.svg
  projects/media/stock.adobe.com/avatar-01-13_256h.png
  projects/media/stock.adobe.com/avatar-02-07.svg
  projects/media/stock.adobe.com/avatar-02-07_256h.png
  projects/media/stock.adobe.com/avatar-02-08.svg
  projects/media/stock.adobe.com/avatar-02-08_256h.png
  projects/media/stock.adobe.com/avatar-02-09.svg
  projects/media/stock.adobe.com/avatar-02-09_256h.png
  projects/media/stock.adobe.com/avatar-02-10.svg
  projects/media/stock.adobe.com/avatar-02-10_256h.png
  projects/media/stock.adobe.com/avatar-02-11.svg
  projects/media/stock.adobe.com/avatar-02-11_256h.png
  projects/media/stock.adobe.com/avatar-02-12.svg
  projects/media/stock.adobe.com/avatar-02-12_256h.png
  projects/media/stock.adobe.com/avatar-02-13.svg
  projects/media/stock.adobe.com/avatar-02-13_256h.png
  projects/webapp/public/assets/avatars/avatar-01-01_256h.png
  projects/webapp/public/assets/avatars/avatar-01-02_256h.png
  projects/webapp/public/assets/avatars/avatar-01-03_256h.png
  projects/webapp/public/assets/avatars/avatar-01-04_256h.png
  projects/webapp/public/assets/avatars/avatar-01-05_256h.png
  projects/webapp/public/assets/avatars/avatar-01-06_256h.png
  projects/webapp/public/assets/avatars/avatar-02-01_256h.png
  projects/webapp/public/assets/avatars/avatar-02-02_256h.png
  projects/webapp/public/assets/avatars/avatar-02-03_256h.png
  projects/webapp/public/assets/avatars/avatar-02-04_256h.png
  projects/webapp/public/assets/avatars/avatar-02-05_256h.png
  projects/webapp/public/assets/avatars/avatar-02-06_256h.png
  projects/webapp/src/components/avatars/avatar-01-01.vue
  projects/webapp/src/components/avatars/avatar-01-07.vue
  projects/webapp/src/components/avatars/avatar-01-08.vue
  projects/webapp/src/components/avatars/avatar-01-09.vue
  projects/webapp/src/components/avatars/avatar-01-10.vue
  projects/webapp/src/components/avatars/avatar-01-11.vue
  projects/webapp/src/components/avatars/avatar-01-12.vue
  projects/webapp/src/components/avatars/avatar-01-13.vue
  projects/webapp/src/components/avatars/avatar-02-07.vue
  projects/webapp/src/components/avatars/avatar-02-08.vue
  projects/webapp/src/components/avatars/avatar-02-09.vue
  projects/webapp/src/components/avatars/avatar-02-10.vue
  projects/webapp/src/components/avatars/avatar-02-11.vue
  projects/webapp/src/components/avatars/avatar-02-12.vue
  projects/webapp/src/components/avatars/avatar-02-13.vue
  projects/webapp/src/components/avatars/index.ts
  projects/webapp/src/svg.d.ts
  projects/webapp/src/views/AvatarsPage.vue
Labels: enhancement

#50 docs: auto-generated documentation
  docs/404.html
  docs/css/app.9dde46b5.css
  docs/css/app.a2698932.css
  docs/index.html
  docs/js/app.63bd337d.js
  docs/js/app.63bd337d.js.map
  docs/js/app.de693478.js
  docs/js/app.de693478.js.map
Labels: documentation

#52 docs: auto-generated documentation
  docs/404.html
  docs/css/app.97606573.css
  docs/css/app.a2698932.css
  docs/index.html
  docs/js/app.364ca19b.js
  docs/js/app.364ca19b.js.map
  docs/js/app.de693478.js
  docs/js/app.de693478.js.map
Labels: documentation

#53 fix: avatar layout
  projects/webapp/src/views/AvatarsPage.vue
Labels: bug

#57 feat: enable avatar gender preferences
  projects/webapp/build-avatars.js
  projects/webapp/src/stores/avatarStore.ts
  projects/webapp/src/stores/avatars.ts
  projects/webapp/src/stores/themeStore.ts
  projects/webapp/src/views/AvatarsPage.vue
Labels: enhancement

#59 feat: expertise
  projects/webapp/src/components/OurAvatar.vue
  projects/webapp/src/stores/avatarStore.ts
  projects/webapp/src/stores/avatars.ts
  projects/webapp/src/views/AvatarsPage.vue
Labels: enhancement
